"""Load script for inserting minute-by-minute data generated by transform into database."""

from log import get_logger, set_logger
import pandas as pd
from os import environ as ENV
import csv

def connect_to_db():
    """Function that connects to database and returns a connection object."""
    pass

def get_transformed_data() -> pd.DataFrame:
    """Function that reads most recent normalised csv data, and returns a dataframe?"""
    pass

def insert_transformed_data() -> None:
    """Function that calls connect function, and inserts into the Microsoft SQL database
    T-SQL format?"""
    logger = get_logger()
    logger.info("Connecting to database.")
    #connection = connect_to_db()
    logger.info("Successfully connected to database!")

    logger.info("Loading local recent data...")
    #transformed_data = get_transformed_data()
    logger.info("Successfully loaded recent data!")

    logger.info("Inserting data into database setup...")

    """
    INSERT INTO DATABASE THINGS HERE
    """

    logger.info("Successfully inserted data!")



if __name__ == "__main__":
    set_logger()
    insert_transformed_data()